### ISSUE TITLE
gulp dev error

### ISSUE THREAD

**Issue by wiber** [Thinkmill/touchstone-starter#2]
This looks awesome. In an attempt to follow the manual I'm learning about streams gulp and this thing. Any ideas?

[09:59:46] Finished 'serve' after 124 ms
Local Server ready on port 8000
[09:59:46] Finished 'html' after 194 ms
dyld: lazy symbol binding failed: Symbol not found: __ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5ValueEEE
  Referenced from: /Users/wiber/github/touchstone-starter/node_modules/touchstonejs-tasks/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5ValueEEE
  Referenced from: /Users/wiber/github/touchstone-starter/node_modules/touchstonejs-tasks/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

Eliass-MacBook-Pro:touchstone-starter wiber$

**Comment by wiber** [comment]
node server.js works fine though. lovely.

**Comment by sebmck** [comment]
What version of node are you using?

**Comment by JedWatson** [comment]
@wiber I can't replicate this unfortunately, can you provide some more details about your environment? e.g. is touchstone linked, have you done a fresh npm install, node version, etc.

**Comment by sebmck** [comment]
@JedWatson I've seen this error a lot with unstable node versions that include buggy `Symbol` implementations so that's likely the cause.

**Comment by wiber** [comment]
after some more poking around.. 

Local Server ready on port 8000
[09:17:57] Finished 'html' after 210 ms
dyld: lazy symbol binding failed: Symbol not found: __ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5ValueEEE
  Referenced from: /Users/wiber/github/touchstone-starter/node_modules/touchstonejs-tasks/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5ValueEEE
  Referenced from: /Users/wiber/github/touchstone-starter/node_modules/touchstonejs-tasks/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
Eliass-MBP:touchstone-starter wiber$ node --version
v0.10.0
Eliass-MBP:touchstone-starter wiber$ npm --version
1.4.15
Eliass-MBP:touchstone-starter wiber$

**Comment by sebmck** [comment]
v0.10.0 is **really** old. Current is  v0.10.35

**Comment by wiber** [comment]
arriving at the same conclusion, sudo n stable did the trick. I'm mainly using meteor and this was the node. 

Any pointers on how to hook this up with meteor? Giving it a shot..

Thanks guys.
