### ISSUE TITLE
touchStone 0.2.0 and "Switch" component

### ISSUE THREAD

**Issue by anthonywebb** [Thinkmill/touchstone-starter#8]
I saw a new "Swtich" component was added to 0.2.0, wondering how it works?  Any chance it will make it to this demo app?  I was looking for a form input that acted like a checkbox, wondering if "switch" was just that?

**Comment by jossmac** [comment]
Hi Anthony,

That's exactly what it is :) I'll try to get it into this repo when I get the chance

**Comment by anthonywebb** [comment]
@jossmac thanks man, I tried to fork and update to 0.2.0 to try it but I didnt get too far.  Looking forward to checking it out.
